// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lk1TFKEdIkFw2kvmpRCoT2XdT-25ZAE',
    appId: '1:273474640206:web:018bcde153e621d81d261f',
    messagingSenderId: '273474640206',
    projectId: 'new-chat-with-me',
    authDomain: 'new-chat-with-me.firebaseapp.com',
    storageBucket: 'new-chat-with-me.appspot.com',
    measurementId: 'G-GRJT1TJH81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuIhoQsdyelk8urcQ5rZjBwVC8DHP-eB4',
    appId: '1:273474640206:android:dd11991dc14f01a31d261f',
    messagingSenderId: '273474640206',
    projectId: 'new-chat-with-me',
    storageBucket: 'new-chat-with-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBssiA1cXCs9upHCz5bQ4HoT64eTwHXi0',
    appId: '1:273474640206:ios:821fdc58b56f112d1d261f',
    messagingSenderId: '273474640206',
    projectId: 'new-chat-with-me',
    storageBucket: 'new-chat-with-me.appspot.com',
    iosBundleId: 'com.example.newChatWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBssiA1cXCs9upHCz5bQ4HoT64eTwHXi0',
    appId: '1:273474640206:ios:821fdc58b56f112d1d261f',
    messagingSenderId: '273474640206',
    projectId: 'new-chat-with-me',
    storageBucket: 'new-chat-with-me.appspot.com',
    iosBundleId: 'com.example.newChatWithMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_lk1TFKEdIkFw2kvmpRCoT2XdT-25ZAE',
    appId: '1:273474640206:web:a92a4fedbe2262201d261f',
    messagingSenderId: '273474640206',
    projectId: 'new-chat-with-me',
    authDomain: 'new-chat-with-me.firebaseapp.com',
    storageBucket: 'new-chat-with-me.appspot.com',
    measurementId: 'G-Y527TFNRDL',
  );
}
